### ISSUE TITLE
RP011: List of PII

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#576]
### Overview
We need to identify any content in the Research folder with personal identifiable information (PII) so we can move them to a restricted location.

### Action Items
- [x] Read the title of the issue and identify the research plan number 
    - For example, if it says RP001, it refers to Research Plan 1.
- [x] Click on the three dots, and choose Edit 
<img width="200" alt="Screenshot 2024-05-08 at 7 54 56 PM" src="https://github.com/hackforla/internship/assets/57029070/10085120-d390-4308-b903-ce52c408c9fd">

- [x] Update the ### in the name of Resources 2.01 with the research plan number. 
    - If the title says RP001, then update RP### with RP001. 
- [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
- [x] Go to the Research by Participant Type folder in Resources 1.01
- [x] Identify the participant type associated with this research plan
- [x] Choose the gear to update the participant type on the Labels.
    - For example, RP001 is associated with Interns, then choose `Participant Type: Intern`
    -  <img width="407" alt="Screenshot 2024-05-08 at 8 15 24 PM" src="https://github.com/hackforla/internship/assets/57029070/05b86604-51ff-4ed9-8cc3-98a45c515c93">
- [x] After assigning the correct participant type, remove the `Participant Type: missing` label
- [x] Go to the research by plan number in Resources 1.02
- [x] Locate the research plan folder indicated in the title of this issue. 
    - For example, if it says RP001, it refers to Research Plan 1, then locate the folder for RP001 in the Google Drive.
- [x] Copy the link of the Research Plan folder
- [x] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line so it becomes a hyperlink.
- [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
- [x] Go though each item in the research plan folder
- [x] Locate any files with PII
- [x] Open the PII list spreadsheet in Resources 1.03
- [x] Fill out the content of the spreadsheet by adding the filename, Research plan #, link to document, and cohort # 
- [x] If there is no PII content, please leave a comment below
- [x] Put this issue into the Questions/Review column and add 'Ready for Research Lead' label after you are done so the team can review the deliverables at the next meeting
- [ ] Sign off by leads

#### Resources for creating this issue
1.01 [Research by participant type folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=sharing) 
1.02 [Research by plan # and name folder](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03 [PII list](https://docs.google.com/spreadsheets/d/17t_3m5UtFZGKLDnH-LUE2c-Hk2_WwIB4Wb9Kni_obnA/edit?usp=sharing)

#### Resources gathered during the completion of this issue
2.01 [RP011 folder on Google drive](https://drive.google.com/drive/folders/19VVUk28lerENkilEFI8uDiOIOLUWofVC?usp=drive_link)

**Comment by pandanista** [comment]
Hi @anamnasim26 , I am assigning this issue to you. Please follow the steps in this [comment](https://github.com/hackforla/internship/issues/576#issue-2288288407) to finish the issue. 

A few tips that can help you with this issue:
- The personal identifiable information (PII) we are referring to could be any name, school, location, or anything that can potentially identify anyone, including our own team members.  
    - Here is an example:  One survey response contained the name. <img width="500" alt="Screenshot 2024-05-28 at 8 04 28 PM" src="https://github.com/hackforla/internship/assets/57029070/f52a5b02-1ae4-4543-9264-a9f072385a29">
- Please make a comment and/or highlight in the document where you found the PII to inform the team where and what PII you are referring to.
- When searching for the personal identifiable information (PII) in a research plan folder, please make sure to check any links in any document or issue because it could link to another document that contains PII.
    - For example, the file [TWI: RP1: Copy of IS21: Internship Program Research Presentation (WIP) - Appendix](https://docs.google.com/presentation/d/1BbSJckVD6eADkm4t1w551u4kqKp1ZBWnXDgecGaY4JE/edit?usp=sharing) in RP001's folder contains 7 links that directs to other sources:
        - Please click through each of them and check if any of them contains PII.
            - One of the links (the last one) doesn't work, then make a note by highlighting the link and commenting that link doesn't work.
            - The rest 6 links in the Appendix slide (from the one sheet to the sigma file) all contain PII. Highlight and comment on each of the 6 links that it directs to content that contains PII.       
- Please include all the links and names of the documents in the [PII content list](https://docs.google.com/spreadsheets/d/17t_3m5UtFZGKLDnH-LUE2c-Hk2_WwIB4Wb9Kni_obnA/edit?usp=sharing).

Thank you, and let me know if you have any questions.

**Comment by anamnasim26** [comment]
@pandanista I went through the research plan folder from 1.02 only as per the steps mentioned to look for PII. Am I also supposed to go through 1.01 Research by participant type folder?

**Comment by pandanista** [comment]
@anamnasim26 The folder you need to go through and check for PII is RP011's folder, which is the folder you linked in Resources 2.01.

**Comment by pandanista** [comment]
@jinyan0425 Would you please review this issue?

**Comment by jinyan0425** [comment]
@anamnasim26 Anam, thank you so much for your effort and swift completion! It looks pretty good :)

@pandanista I reviewed this issue. As Anam mentioned, Bonnie was mentioned in one of the responses to Question 1.04 - "How could we improve today's workshop". So there are two PIIs:
 
1. In the [TWE: LinkedIn Workshop Exit Survey (Responses)](https://docs.google.com/spreadsheets/d/1x0beS-RhEJUKHCGFMf4XlaEx1vV686al1pMwLp8ijtc/edit?usp=sharing): row 13 and column AW. @anamnasim26 has recorded this in the [PII list](https://docs.google.com/spreadsheets/d/17t_3m5UtFZGKLDnH-LUE2c-Hk2_WwIB4Wb9Kni_obnA/edit?usp=sharing) in _row 72_. I made some minor updates to her note for our reference, clearly specifying the column numbers and the corresponding names mentioned.
2. In the [TWE: LinkedIn Workshop Exit Survey - the response tab](https://docs.google.com/forms/d/16QcDQtLTPEct44sJ_RIudj6XuKK0FwZdsAcu3B1BMeo/edit#responses): responses to question 1.04. I added this to the [PII list](https://docs.google.com/spreadsheets/d/17t_3m5UtFZGKLDnH-LUE2c-Hk2_WwIB4Wb9Kni_obnA/edit?usp=sharing) in _row 73_. **With this in mind, I'm wondering what our standard solution is, as each survey has its own response tab. Would it be possible to remove the responses from there and store them solely in a separate spreadsheet?**

**Comment by pandanista** [comment]
@jinyan0425 Thank you for reviewing this issue. 
- I found a similar situation in a closed issue, and see the solution in this [comment](https://github.com/hackforla/internship/issues/575#issuecomment-2181167316).
    - Would the solution for RP010 be sufficient to solve this situation? 
    - If so, would you please write a similar instructions for Anam to finish the de-identification of the survey responses?
    - Would you add Anam to the PII drive and make her Content Manager for the de-identification? Appreciate it.

**Comment by jinyan0425** [comment]
@anamnasim26 

As mentioned in point 2 in this [comment](https://github.com/hackforla/internship/issues/576#issuecomment-2373094018), there are PII in the [TWE: LinkedIn Workshop Exit Survey - the response tab](https://docs.google.com/forms/d/16QcDQtLTPEct44sJ_RIudj6XuKK0FwZdsAcu3B1BMeo/edit#responses). Could you please follow the action items below to de-identify the survey responses? I have added you to the PII drive as a Content Manager

De-identify [the survey responses in the form](https://docs.google.com/forms/d/16QcDQtLTPEct44sJ_RIudj6XuKK0FwZdsAcu3B1BMeo/edit#responses) by following the steps:
- [ ] Create a spreadsheet that corresponds with the survey responses by choosing 'Link to Sheets'. This sheet will be referred as spreadsheet A in the following steps.
- [ ] Unlink the Google form from the spreadsheet A
- [ ] Delete the existing responses from the Google form
- [ ] Add a sheet (spreadsheet B) to the responses sheet you just generated (spreadsheet A), and in spreadsheet B, 
   - [ ] Add a link to the Google form
   - [ ] Add a link to the research plan's wiki page
- [ ] Rename the spreadsheet document that contains spreadsheets A and B by adding the research plan number in the document name so team members can identify the research plan the spreadsheets are associated with easily. 
- [ ] Move the spreadsheet document that contains spreadsheets A and B to the corresponding research plan folder under a folder on the Internship-PII drive called: delete when research plan complete.
    - The path is Internship - PII > Delete when research plan complete > RP010 
- [ ] Make a copy of the spreadsheet document that contains spreadsheets A and B so you can start to de-identify survey responses in the next step if needed
- [ ] De-identify the survey responses in the copy of the spreadsheet document that contains spreadsheets A and B if needed
- [ ] Move the new de-identified spreadsheet document to the research plan folder on the Internship > Internships > Research > Research by Plan # and Name > RP010 folder
- [ ] Rename the new de-identified sheet by removing `Copy of Copy of ` and adding `[De-identified]` to the beginning of the file name
-  [ ] Go to Internship - PII > Delete when research plan complete > RP010 (if it is not already open)
- [ ] Delete the copy of the spreadsheet document that contains spreadsheets A and B you previously made to de-identify PII. 
    - [ ] If you can't delete the file in the Internship - PII drive, please link the file in a new comment in this issue, and let the lead know so they can delete the file for you.

**Comment by jinyan0425** [comment]
> [@jinyan0425](https://github.com/jinyan0425) Thank you for reviewing this issue.
> 
> * I found a similar situation in a closed issue, and see the solution in this [comment](https://github.com/hackforla/internship/issues/575#issuecomment-2181167316).
>   
>   * Would the solution for RP010 be sufficient to solve this situation?
>   * If so, would you please write a similar instructions for Anam to finish the de-identification of the survey responses?
>   * Would you add Anam to the PII drive and make her Content Manager for the de-identification? Appreciate it.

**DONE in the [comment](https://github.com/hackforla/internship/issues/576#issuecomment-2375428811) below.**

**Comment by anamnasim26** [comment]
@pandanista and @jinyan0425 I am so lost regarding the point 4 (b) that says add a link to the research plans wiki page. I am confused what is the Wiki page?

**Comment by pandanista** [comment]
@anamnasim26 
- Wiki is where we store information about the entire project, for example, all the research plans. 
    - TWE project's Wiki starts [here](https://github.com/hackforla/internship/wiki). 
    - I recommend spending some time navigating around the wiki to get familiar with the content stored under the [research output overview section](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- The research plan's wiki page in 4(b) refers to RP011's wiki page, which can be found from [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview) > Research by Plan Number > Research Plan 11. Once you get to RP011's wiki page, you can copy the url of the RP011's wiki page, and paste in the spreadsheet.
- I have adjusted your access level in the shared Google drive. Hopefully you can move the files now. Thank you for catching that.

**Comment by anamnasim26** [comment]
@pandanista, I am still unable to move files from Internship drive to Internship - PII drive.

**Comment by jinyan0425** [comment]
@anamnasim26 You have been added as a content manager.![image](https://github.com/user-attachments/assets/8b58f23d-6a02-4125-a4e7-38ab42b6c709) 

Did you receive the email notification?

Could you please check it @pandanista? Thank you so much! I am about to depart!

**Comment by anamnasim26** [comment]
@pandanista @jinyan0425 
I got a notification, but when I was trying to move the document to the Internship - PII folder, it was greyed out for me 
![Image](https://github.com/user-attachments/assets/efe3f8a9-d270-4c4e-8ab7-53c3ef16475a)

**Comment by pandanista** [comment]
That is odd, I guess it must have something to do with the Google drive settings.

No worries. I went ahead and moved [TWE: LinkedIn Workshop Exit Survey (Responses)](https://docs.google.com/spreadsheets/d/1x0beS-RhEJUKHCGFMf4XlaEx1vV686al1pMwLp8ijtc/edit?usp=drive_link) to the Internship-PII drive > Delete when research plans complete > RP011. Let us know if you have more questions.

**Comment by pandanista** [comment]
@anamnasim26 I just adjusted your settings from Content Manager to Manager. Please keep us posted if that solves the problem when you need to move another file in the upcoming steps.

**Comment by pandanista** [comment]
@anamnasim26 
Would you please provide an update?
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" - we know you just came back from break, please just summarize the progress from before then
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by anamnasim26** [comment]
@pandanista @jinyan0425 I have just now finished the de identification. everything is done. Just moving this to get checked by you guys now.

**Comment by pandanista** [comment]
@anamnasim26:

Thank you for working this issue!

I just reviewed [the sheet you created](https://docs.google.com/spreadsheets/d/14BcuCVPDP7bFxRO2Xb1ZaZZo3f5T1SJoYrjNa_fD9yA/edit?usp=sharing), and have a few questions.
- what is the tab `form responses 2` for?
- What is `Form Responses 1`?
- In spreadsheet B, the instructions above says to include the google form link, but I don't see it. I just added a row called Google Form survey. Would you please include the survey link? <img width="700" alt="Screenshot 2024-10-15 at 2 47 25 PM" src="https://github.com/user-attachments/assets/e1dacd82-e7c3-4f9e-98aa-4b95988b6c2d">
- The spreadsheet needs to be renamed based on the instruction, but it doesn't look like it's been renamed. Would you please take care of that? <img width="687" alt="Screenshot 2024-10-15 at 2 49 00 PM" src="https://github.com/user-attachments/assets/a22450bf-1834-4f4d-845a-47d45977811e">
- Also, in [this spreadsheet](https://docs.google.com/spreadsheets/d/1x0beS-RhEJUKHCGFMf4XlaEx1vV686al1pMwLp8ijtc/edit?usp=sharing), does it still have the OG responses?

**Comment by KC-skc** [comment]
@anamnasim26 
Please provide update

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by pandanista** [comment]
- offboarded Anam
- Putting this issue back to the prioritized backlog column
- Will assign this issue to another team member to finish where she is left off.

**Comment by pandanista** [comment]
- I have reviewed and cleaned up the response sheet.
- I have also made a copy and de-identified the spreadsheet before making an other copy of [the de-identified spreadsheet](https://docs.google.com/spreadsheets/d/1jGd-rod31z9wsTDi_UWbS39cP6v1eoQpHPj0LkUwuy0/edit?usp=drive_link) with no version history, which is now saved in the internship's RP011 folder.
- Closing this issue now as all steps are completed.
